### ISSUE TITLE
AFKStatusChangeEvent not working properly

### ISSUE THREAD

**Issue by joex92** [teakivy/teaks-tweaks#148]
**Describe the bug**
When setting up a DiscordSRV event for the AFK event, the `isAfk()` method returns always `false`

**To Reproduce**
1. install discordsrv and setup the bot
2. setup an AFK alert
3. be AFK in-game
4. see messages sent to discord

**Paste**
> Run `/teakstweaks paste` and include the generated link.
> ***Note:** This also provides server logs, if you would like to exclude these, use `/teakstweaks paste false`.*

not working, I get this error for that command: `java.io.IOException: Request failed with status code: 502`

**Expected behavior**
show when it's AFK and when it's not.

**Screenshots**
Console [Bloom hosting]:
![Image](https://github.com/user-attachments/assets/9106276c-439c-49ce-9c98-efcac9257096)
Discord [GMT-5]:
![Image](https://github.com/user-attachments/assets/20e5e052-1fb0-4fe4-9058-02066b1fa93a)

**Additional context**
alert setup (server's in Spanish):
```yaml
  - Trigger: AFKStatusChangeEvent 
    Channel: global
    Embed:
      Color: "#${isAfk() ? 'ff7f7f' : '7fff7f'}"
      Author:
        ImageUrl: "{embedavatarurl}"
        Name: "${getPlayer().getName() + (isAfk() ? ' ' : ' ya no ') + 'está AFK'}"
        Url: ""
      ThumbnailUrl: ""
      Title:
        Text: ""
        Url: ""
      Description: "${isAfk()}"
      Fields: []
      ImageUrl: ""
      Footer:
        Text: ""
        IconUrl: ""
      Timestamp: false
```
I added the raw value on the description section to debug it...
